### ISSUE TITLE
module 'torch_quiver' has no attribute 'device_quiver_from_csr_array'

### ISSUE THREAD

**Issue by xcwanAndy** [quiver-team/torch-quiver#131]
Hi, I found an error when using torch-quiver==0.1.1 and tried to run [example](https://github.com/quiver-team/torch-quiver/blob/main/examples/pyg/reddit_quiver.py).

The error is
```
Traceback (most recent call last):
  File "reddit_quiver.py", line 29, in <module>
    quiver_sampler = quiver.pyg.GraphSageSampler(csr_topo, sizes=[25, 10], device=0, mode='GPU') # Quiver
  File "/usr/local/lib/python3.6/dist-packages/quiver/pyg/sage_sampler.py", line 72, in __init__
    self.quiver = qv.device_quiver_from_csr_array(self.csr_topo.indptr,
AttributeError: module 'torch_quiver' has no attribute 'device_quiver_from_csr_array'
```

Is there any suggestion for it?

**Comment by prenc** [comment]
Hi @xcwanAndy, I've come across the same problem. My investigation has shown that the error appears when Quiver is not compiled/built properly. The `torch_quiver` extension module lacks cuda versions of functions. It might happen when cuda is not available during the package installation due to the way the installer figures out whether to build them ([code](https://github.com/quiver-team/torch-quiver/blob/0592669225954e46d9c57c0ca121c365af47b57f/setup.py#L23)).

I am not that experienced, but it seems to be a bug for me to rely on the torch notion of cuda availability during deps installation.

**Comment by LukeLIN-web** [comment]
> 

same as me, it happens on env from https://github.com/quiver-team/torch-quiver/blob/main/docker/Dockerfile

**Comment by LukeLIN-web** [comment]
> > 
> 
> same as me, it happens on env from https://github.com/quiver-team/torch-quiver/blob/main/docker/Dockerfile

I figure it out, because I use a A100 GPU. compiled codes cannot run at A100. I change to V100 and run successfully.
